/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FileId = IDL.Nat;
export const ContactStatus = IDL.Variant({
  'Blocked' : IDL.Null,
  'Accepted' : IDL.Null,
  'Pending' : IDL.Null,
});
export const ExportContact = IDL.Record({
  'status' : ContactStatus,
  'addedAt' : IDL.Int,
  'principalText' : IDL.Text,
});
export const ExportData = IDL.Record({
  'contacts' : IDL.Vec(ExportContact),
  'exportedAt' : IDL.Int,
  'profile' : IDL.Record({
    'bio' : IDL.Text,
    'emailVerified' : IDL.Bool,
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  }),
});
export const FileMetadata = IDL.Record({
  'id' : FileId,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'size' : IDL.Nat64,
  'fileType' : IDL.Text,
  'uploadDate' : IDL.Int,
});
export const PublicProfile = IDL.Record({
  'bio' : IDL.Text,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'lastSeen' : IDL.Int,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const StatusUpdate = IDL.Record({
  'id' : IDL.Nat,
  'postedAt' : IDL.Int,
  'content' : IDL.Text,
  'expiresAt' : IDL.Int,
  'author' : IDL.Principal,
  'mediaBlob' : IDL.Opt(ExternalBlob),
  'reactions' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text)),
});
export const Contact = IDL.Record({
  'status' : ContactStatus,
  'principal' : IDL.Principal,
  'addedAt' : IDL.Int,
});
export const GroupInfo = IDL.Record({
  'admin' : IDL.Principal,
  'name' : IDL.Text,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const ConversationType = IDL.Variant({
  'Group' : IDL.Null,
  'Direct' : IDL.Null,
});
export const ConversationPreview = IDL.Record({
  'id' : IDL.Nat,
  'members' : IDL.Vec(PublicProfile),
  'lastMessageTime' : IDL.Opt(IDL.Int),
  'unreadCount' : IDL.Nat,
  'groupInfo' : IDL.Opt(GroupInfo),
  'conversationType' : ConversationType,
});
export const DisappearingTimer = IDL.Variant({
  'Off' : IDL.Null,
  'Days30' : IDL.Null,
  'Days7' : IDL.Null,
  'Hours24' : IDL.Null,
});
export const EncryptedEmailConfig = IDL.Record({
  'senderEmail' : IDL.Text,
  'encryptedApiKey' : IDL.Vec(IDL.Nat8),
});
export const MessageType = IDL.Variant({
  'File' : IDL.Null,
  'Text' : IDL.Null,
  'Image' : IDL.Null,
  'Audio' : IDL.Null,
  'Video' : IDL.Null,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'deleted' : IDL.Bool,
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'messageType' : MessageType,
  'conversationId' : IDL.Nat,
  'mediaBlob' : IDL.Opt(ExternalBlob),
  'timestamp' : IDL.Int,
  'mediaName' : IDL.Opt(IDL.Text),
  'mediaSize' : IDL.Opt(IDL.Nat64),
  'replyToId' : IDL.Opt(IDL.Nat),
  'reactions' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text)),
});
export const WrappedGroupKey = IDL.Record({
  'encryptedKey' : IDL.Vec(IDL.Nat8),
  'wrappedBy' : IDL.Principal,
});
export const NotificationKind = IDL.Variant({
  'ContactRequest' : IDL.Null,
  'StatusReaction' : IDL.Null,
  'Mention' : IDL.Null,
  'ContactAccepted' : IDL.Null,
  'NewMessage' : IDL.Null,
  'GroupInvite' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'kind' : NotificationKind,
  'read' : IDL.Bool,
  'fromPrincipal' : IDL.Opt(IDL.Principal),
  'conversationId' : IDL.Opt(IDL.Nat),
  'timestamp' : IDL.Int,
});
export const Profile = IDL.Record({
  'bio' : IDL.Text,
  'twoFactorEnabled' : IDL.Bool,
  'emailVerified' : IDL.Bool,
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'lastSeen' : IDL.Int,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpRequestResult = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpRequestResult,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'acceptContactRequest' : IDL.Func([IDL.Principal], [], []),
  'addContactByPrincipal' : IDL.Func([IDL.Text], [], []),
  'addGroupMember' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'addReaction' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'clearGroupKeys' : IDL.Func([IDL.Nat], [], []),
  'createGroup' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Principal), IDL.Opt(ExternalBlob)],
      [IDL.Nat],
      [],
    ),
  'deleteFile' : IDL.Func([FileId], [], []),
  'deleteMessage' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'deleteStatus' : IDL.Func([IDL.Nat], [], []),
  'exportUserData' : IDL.Func([], [ExportData], ['query']),
  'getAllFiles' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
  'getBlockedUsers' : IDL.Func([], [IDL.Vec(PublicProfile)], ['query']),
  'getContactStatuses' : IDL.Func([], [IDL.Vec(StatusUpdate)], ['query']),
  'getContacts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Contact, PublicProfile))],
      ['query'],
    ),
  'getConversations' : IDL.Func([], [IDL.Vec(ConversationPreview)], ['query']),
  'getDisappearingTimer' : IDL.Func([IDL.Nat], [DisappearingTimer], ['query']),
  'getEmailVerificationStatus' : IDL.Func(
      [],
      [IDL.Record({ 'verified' : IDL.Bool, 'email' : IDL.Opt(IDL.Text) })],
      ['query'],
    ),
  'getEncryptedEmailConfig' : IDL.Func(
      [],
      [IDL.Opt(EncryptedEmailConfig)],
      ['query'],
    ),
  'getFile' : IDL.Func([FileId], [FileMetadata], ['query']),
  'getGroupInfo' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'members' : IDL.Vec(PublicProfile),
          'admin' : IDL.Principal,
          'name' : IDL.Text,
          'avatar' : IDL.Opt(ExternalBlob),
        }),
      ],
      ['query'],
    ),
  'getMessages' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Int), IDL.Nat],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getMyGroupKey' : IDL.Func([IDL.Nat], [IDL.Opt(WrappedGroupKey)], ['query']),
  'getMyStatuses' : IDL.Func([], [IDL.Vec(StatusUpdate)], ['query']),
  'getNotifications' : IDL.Func([IDL.Nat], [IDL.Vec(Notification)], ['query']),
  'getPendingRequests' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Contact, PublicProfile))],
      ['query'],
    ),
  'getProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getPublicKey' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  'getPublicKeys' : IDL.Func(
      [IDL.Vec(IDL.Principal)],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(IDL.Nat8)))],
      ['query'],
    ),
  'getPublicProfile' : IDL.Func([IDL.Principal], [PublicProfile], ['query']),
  'getShareId' : IDL.Func([], [IDL.Text], ['query']),
  'getTwoFactorStatus' : IDL.Func(
      [],
      [
        IDL.Record({
          'emailVerified' : IDL.Bool,
          'email' : IDL.Opt(IDL.Text),
          'enabled' : IDL.Bool,
        }),
      ],
      ['query'],
    ),
  'getTypingUsers' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Principal)], ['query']),
  'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getVetKdPublicKey' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'getVetKey' : IDL.Func([IDL.Vec(IDL.Nat8)], [IDL.Vec(IDL.Nat8)], []),
  'importUserData' : IDL.Func(
      [ExportData],
      [IDL.Record({ 'contactsRequested' : IDL.Nat })],
      [],
    ),
  'leaveGroup' : IDL.Func([IDL.Nat], [], []),
  'markAsRead' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'markNotificationsRead' : IDL.Func([IDL.Nat], [], []),
  'postStatus' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [IDL.Nat], []),
  'publishGroupKeys' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(IDL.Nat8)))],
      [],
      [],
    ),
  'publishPublicKey' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
  'reactToStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'rejectContactRequest' : IDL.Func([IDL.Principal], [], []),
  'removeContact' : IDL.Func([IDL.Principal], [], []),
  'removeGroupMember' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'removeReaction' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'reportUser' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'requestEmailVerification' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'requestLoginOtp' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(PublicProfile)], ['query']),
  'sendContactRequest' : IDL.Func([IDL.Principal], [], []),
  'sendMessage' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        MessageType,
        IDL.Opt(ExternalBlob),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat64),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Vec(IDL.Principal)),
      ],
      [IDL.Nat],
      [],
    ),
  'setDisappearingTimer' : IDL.Func([IDL.Nat, DisappearingTimer], [], []),
  'setEncryptedEmailConfig' : IDL.Func([IDL.Vec(IDL.Nat8), IDL.Text], [], []),
  'setProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)], [], []),
  'setTwoFactorEnabled' : IDL.Func([IDL.Bool], [], []),
  'setTyping' : IDL.Func([IDL.Nat], [], []),
  'startDirectChat' : IDL.Func([IDL.Principal], [IDL.Nat], []),
  'toggleNotificationRead' : IDL.Func([IDL.Nat], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unblockUser' : IDL.Func([IDL.Principal], [], []),
  'updateGroup' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'uploadFile' : IDL.Func(
      [IDL.Text, IDL.Nat64, IDL.Text, ExternalBlob],
      [FileMetadata],
      [],
    ),
  'verifyEmailOtp' : IDL.Func([IDL.Text], [], []),
  'verifyLoginOtp' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FileId = IDL.Nat;
  const ContactStatus = IDL.Variant({
    'Blocked' : IDL.Null,
    'Accepted' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const ExportContact = IDL.Record({
    'status' : ContactStatus,
    'addedAt' : IDL.Int,
    'principalText' : IDL.Text,
  });
  const ExportData = IDL.Record({
    'contacts' : IDL.Vec(ExportContact),
    'exportedAt' : IDL.Int,
    'profile' : IDL.Record({
      'bio' : IDL.Text,
      'emailVerified' : IDL.Bool,
      'name' : IDL.Text,
      'email' : IDL.Opt(IDL.Text),
    }),
  });
  const FileMetadata = IDL.Record({
    'id' : FileId,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'size' : IDL.Nat64,
    'fileType' : IDL.Text,
    'uploadDate' : IDL.Int,
  });
  const PublicProfile = IDL.Record({
    'bio' : IDL.Text,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'lastSeen' : IDL.Int,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const StatusUpdate = IDL.Record({
    'id' : IDL.Nat,
    'postedAt' : IDL.Int,
    'content' : IDL.Text,
    'expiresAt' : IDL.Int,
    'author' : IDL.Principal,
    'mediaBlob' : IDL.Opt(ExternalBlob),
    'reactions' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text)),
  });
  const Contact = IDL.Record({
    'status' : ContactStatus,
    'principal' : IDL.Principal,
    'addedAt' : IDL.Int,
  });
  const GroupInfo = IDL.Record({
    'admin' : IDL.Principal,
    'name' : IDL.Text,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const ConversationType = IDL.Variant({
    'Group' : IDL.Null,
    'Direct' : IDL.Null,
  });
  const ConversationPreview = IDL.Record({
    'id' : IDL.Nat,
    'members' : IDL.Vec(PublicProfile),
    'lastMessageTime' : IDL.Opt(IDL.Int),
    'unreadCount' : IDL.Nat,
    'groupInfo' : IDL.Opt(GroupInfo),
    'conversationType' : ConversationType,
  });
  const DisappearingTimer = IDL.Variant({
    'Off' : IDL.Null,
    'Days30' : IDL.Null,
    'Days7' : IDL.Null,
    'Hours24' : IDL.Null,
  });
  const EncryptedEmailConfig = IDL.Record({
    'senderEmail' : IDL.Text,
    'encryptedApiKey' : IDL.Vec(IDL.Nat8),
  });
  const MessageType = IDL.Variant({
    'File' : IDL.Null,
    'Text' : IDL.Null,
    'Image' : IDL.Null,
    'Audio' : IDL.Null,
    'Video' : IDL.Null,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'deleted' : IDL.Bool,
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'messageType' : MessageType,
    'conversationId' : IDL.Nat,
    'mediaBlob' : IDL.Opt(ExternalBlob),
    'timestamp' : IDL.Int,
    'mediaName' : IDL.Opt(IDL.Text),
    'mediaSize' : IDL.Opt(IDL.Nat64),
    'replyToId' : IDL.Opt(IDL.Nat),
    'reactions' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text)),
  });
  const WrappedGroupKey = IDL.Record({
    'encryptedKey' : IDL.Vec(IDL.Nat8),
    'wrappedBy' : IDL.Principal,
  });
  const NotificationKind = IDL.Variant({
    'ContactRequest' : IDL.Null,
    'StatusReaction' : IDL.Null,
    'Mention' : IDL.Null,
    'ContactAccepted' : IDL.Null,
    'NewMessage' : IDL.Null,
    'GroupInvite' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'kind' : NotificationKind,
    'read' : IDL.Bool,
    'fromPrincipal' : IDL.Opt(IDL.Principal),
    'conversationId' : IDL.Opt(IDL.Nat),
    'timestamp' : IDL.Int,
  });
  const Profile = IDL.Record({
    'bio' : IDL.Text,
    'twoFactorEnabled' : IDL.Bool,
    'emailVerified' : IDL.Bool,
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'lastSeen' : IDL.Int,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpRequestResult = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpRequestResult,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'acceptContactRequest' : IDL.Func([IDL.Principal], [], []),
    'addContactByPrincipal' : IDL.Func([IDL.Text], [], []),
    'addGroupMember' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'addReaction' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'clearGroupKeys' : IDL.Func([IDL.Nat], [], []),
    'createGroup' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Principal), IDL.Opt(ExternalBlob)],
        [IDL.Nat],
        [],
      ),
    'deleteFile' : IDL.Func([FileId], [], []),
    'deleteMessage' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'deleteStatus' : IDL.Func([IDL.Nat], [], []),
    'exportUserData' : IDL.Func([], [ExportData], ['query']),
    'getAllFiles' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
    'getBlockedUsers' : IDL.Func([], [IDL.Vec(PublicProfile)], ['query']),
    'getContactStatuses' : IDL.Func([], [IDL.Vec(StatusUpdate)], ['query']),
    'getContacts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Contact, PublicProfile))],
        ['query'],
      ),
    'getConversations' : IDL.Func(
        [],
        [IDL.Vec(ConversationPreview)],
        ['query'],
      ),
    'getDisappearingTimer' : IDL.Func(
        [IDL.Nat],
        [DisappearingTimer],
        ['query'],
      ),
    'getEmailVerificationStatus' : IDL.Func(
        [],
        [IDL.Record({ 'verified' : IDL.Bool, 'email' : IDL.Opt(IDL.Text) })],
        ['query'],
      ),
    'getEncryptedEmailConfig' : IDL.Func(
        [],
        [IDL.Opt(EncryptedEmailConfig)],
        ['query'],
      ),
    'getFile' : IDL.Func([FileId], [FileMetadata], ['query']),
    'getGroupInfo' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'members' : IDL.Vec(PublicProfile),
            'admin' : IDL.Principal,
            'name' : IDL.Text,
            'avatar' : IDL.Opt(ExternalBlob),
          }),
        ],
        ['query'],
      ),
    'getMessages' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Int), IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getMyGroupKey' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(WrappedGroupKey)],
        ['query'],
      ),
    'getMyStatuses' : IDL.Func([], [IDL.Vec(StatusUpdate)], ['query']),
    'getNotifications' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getPendingRequests' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Contact, PublicProfile))],
        ['query'],
      ),
    'getProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getPublicKey' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    'getPublicKeys' : IDL.Func(
        [IDL.Vec(IDL.Principal)],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(IDL.Nat8)))],
        ['query'],
      ),
    'getPublicProfile' : IDL.Func([IDL.Principal], [PublicProfile], ['query']),
    'getShareId' : IDL.Func([], [IDL.Text], ['query']),
    'getTwoFactorStatus' : IDL.Func(
        [],
        [
          IDL.Record({
            'emailVerified' : IDL.Bool,
            'email' : IDL.Opt(IDL.Text),
            'enabled' : IDL.Bool,
          }),
        ],
        ['query'],
      ),
    'getTypingUsers' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Principal)], ['query']),
    'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getVetKdPublicKey' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'getVetKey' : IDL.Func([IDL.Vec(IDL.Nat8)], [IDL.Vec(IDL.Nat8)], []),
    'importUserData' : IDL.Func(
        [ExportData],
        [IDL.Record({ 'contactsRequested' : IDL.Nat })],
        [],
      ),
    'leaveGroup' : IDL.Func([IDL.Nat], [], []),
    'markAsRead' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'markNotificationsRead' : IDL.Func([IDL.Nat], [], []),
    'postStatus' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [IDL.Nat], []),
    'publishGroupKeys' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(IDL.Nat8)))],
        [],
        [],
      ),
    'publishPublicKey' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
    'reactToStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'rejectContactRequest' : IDL.Func([IDL.Principal], [], []),
    'removeContact' : IDL.Func([IDL.Principal], [], []),
    'removeGroupMember' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'removeReaction' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'reportUser' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'requestEmailVerification' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'requestLoginOtp' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(PublicProfile)], ['query']),
    'sendContactRequest' : IDL.Func([IDL.Principal], [], []),
    'sendMessage' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          MessageType,
          IDL.Opt(ExternalBlob),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat64),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Vec(IDL.Principal)),
        ],
        [IDL.Nat],
        [],
      ),
    'setDisappearingTimer' : IDL.Func([IDL.Nat, DisappearingTimer], [], []),
    'setEncryptedEmailConfig' : IDL.Func([IDL.Vec(IDL.Nat8), IDL.Text], [], []),
    'setProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'setTwoFactorEnabled' : IDL.Func([IDL.Bool], [], []),
    'setTyping' : IDL.Func([IDL.Nat], [], []),
    'startDirectChat' : IDL.Func([IDL.Principal], [IDL.Nat], []),
    'toggleNotificationRead' : IDL.Func([IDL.Nat], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unblockUser' : IDL.Func([IDL.Principal], [], []),
    'updateGroup' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'uploadFile' : IDL.Func(
        [IDL.Text, IDL.Nat64, IDL.Text, ExternalBlob],
        [FileMetadata],
        [],
      ),
    'verifyEmailOtp' : IDL.Func([IDL.Text], [], []),
    'verifyLoginOtp' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };